import 'package:flutter/material.dart';
import 'package:flutter_vector_icons/flutter_vector_icons.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:line_awesome_flutter/line_awesome_flutter.dart';

const _base = 'assets/';
const _lottieBase = "${_base}lottie/";
const _imageBase = "${_base}images/";
const _iconBase = "${_base}icons/";
const _videoBase = "${_base}videos/";

// Lottie (Json) ---------------------------------------------------------------
const loadingJson = "${_lottieBase}loading_circular.json";
const warningJson = "${_lottieBase}warning.json";
const successJson = "${_lottieBase}success.json";
const errorJson = "${_lottieBase}error.json";
const infoJson = "${_lottieBase}info.json";
const emptyJson = "${_lottieBase}empty.json";
const welcomeJson = "${_lottieBase}welcome.json";
const unauthorizedJson = "${_lottieBase}unauthorized.json";

// Images ----------------------------------------------------------------------
const defaultAvatar = "${_imageBase}default_avatar.jpg";
const logoCoverImage = "${_imageBase}logo_cover.png";
const appIcon = "${_imageBase}app_icon.png";
const mybooking = "${_imageBase}my_booking.png";
const mybookingWhite = "${_imageBase}My_booking_white.png";
const booking = "${_imageBase}booking1.png";
const chaletImage = "${_imageBase}chalet.jpg";
const hotelImage = "${_imageBase}hotel.jpg";
const floosakImage = "${_imageBase}floosak.png";

// Icons -----------------------------------------------------------------------
const externalLinkIcon = Feather.external_link;
const homeIcon = Feather.home;
const userIcon = Feather.user;
const settingsIcon = Feather.settings;
const languageIcon = Feather.globe;
const darkModeIcon = Feather.moon; //LineAwesomeIcons.moon
const lightModeIcon = LineAwesomeIcons.sun;
const privacyPolicyIcon = Feather.lock;
const termsOfUseIcon = Feather.shield;
const searchIcon = Feather.search;
const imageIcon = Feather.image;
const dropDownIcon = Icons.arrow_drop_down_rounded;
const infoIcon = Feather.info;
const dateIcon = Feather.calendar;
const radioOnIcon = Ionicons.radio_button_on_outline;
const radioOffIcon = Ionicons.radio_button_off_outline;
const visibleIcon = Icons.visibility;
const invisibleIcon = Icons.visibility_off;
const addIcon = Icons.add_rounded;
const timeIcon = Feather.clock;
const calendarIcon = Feather.calendar;
const starIcon = Icons.star_rounded;
const starBorderIcon = Icons.star_border_outlined;
const deleteOutIcon = Icons.delete_outline_rounded;
const callIcon = Icons.phone_rounded;
const phoneIcon = Icons.phone_iphone_rounded;
const emailIcon = Icons.email_outlined;
const mapIcon = Icons.location_on_outlined;
const bookingIcon = Icons.sticky_note_2_outlined;
const favoriteIcon = Icons.favorite_outline_outlined;
const favoriteFullIcon = Icons.favorite;
const personIcon = Icons.person_2_outlined;
const priceIcon = Icons.monetization_on_outlined;
const periodIcon = Icons.calendar_today;
const calenderIcon = Icons.calendar_today_outlined;
const priceCheckIcon = Icons.price_check_rounded;
const moneyIcon =Icons.money;
const priceChangeIcon =Icons.price_change;
const rangeDataIcon = Icons.date_range;
const groupsIcon = Icons.groups_2_outlined;
const depositIcon = Icons.money_off_sharp;
const accessTimeIcon = Icons.access_time;
const arrowBackIcon = Icon(Icons.arrow_back_ios);
const arrowBacksIcon = Icons.arrow_back_ios;
const arrowForWordIcon = Icons.arrow_forward;
const angleLeftIcon = LineAwesomeIcons.angle_left_solid;
const angleRightIcon = LineAwesomeIcons.angle_right_solid;
const goBackIcon =Icons.arrow_back;
const cameraIcon = Icons.camera_alt_outlined;
const cameraSourceIcon = Icons.camera_alt;
const gallerySourceIcon = Icons.photo;

const hotelIcon = Icons.hotel;
const poolIcon = Icons.pool;
const doveIcon = FontAwesomeIcons.dove;
const defaultFacilityIcon = Icons.home_work;
const whatsappIcon = FaIcon(FontAwesomeIcons.whatsapp);
const trueIcon = Icons.tune;
const notificationIcon = Icons.notification_important_outlined;
const arrowdownIcon = Icons.arrow_downward;
const arrowupIcon = Icons.arrow_upward;
const refreshIcon = Icons.refresh;
const errorIcon = Icons.error;
const shareIcon = Icons.share;
const apartmentIcon = Icons.apartment;
const logoutIcon = Icons.logout;
const loginIcon =Icons.login;
const playListIcon = Icons.playlist_add_check_rounded;
const personalIcon = Icons.personal_injury_outlined;
const groups2Icon =Icons.groups_2;
const peopleIcon =Icons.people;
const childIcon =Icons.child_care;
const facebookIcon = LineAwesomeIcons.facebook;
const instagramIcon = LineAwesomeIcons.instagram;
const whatsappInIcon =FontAwesomeIcons.whatsapp;
const pauseIcon = Icons.pause;
const playArrowIcon = Icons.play_arrow;
const userCircleIcon =  LineAwesomeIcons.user_circle;
const cogIcon =LineAwesomeIcons.cog_solid;
const bookOpenIcon =LineAwesomeIcons.book_open_solid;
const headSetIcon = LineAwesomeIcons.headset_solid;
const singInIcon =LineAwesomeIcons.sign_in_alt_solid;
const deleteIcon = Icons.delete_forever;
const checkIcon =Icons.check_circle;
const closeIcon = Icons.close;
const radioCheckIcon = Icons.radio_button_checked;
const radioOutIcon =Icons.radio_button_off;
const truesIcon =Icons.check;
